name: isit_restaurantes_app
description: Aplicación para restaurantes y negocios de comida.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/img/logo_ISIT_colors.png
    - assets/img/pepperoni-jalapeno-pizza.jpg
    - assets/img/guantes-dedo-corto-moto-y-de-usos-multiples-D_NQ_NP_797505-MLA25043007678_092016-O.jpg
    - assets/img/logo-snippet.png
    - assets/img/PAGINA_DE_ATERRIZAJE__2_.jpg
    - assets/img/Rappi_backgr_logo.png
    - assets/img/uber-eats-logo-1.png
    - assets/img/logo.png
    - assets/img/cm1.jpeg
    - assets/img/cm2.jpeg
    - assets/img/cm3.jpeg
    - assets/img/cm4.jpeg
    - assets/img/food1.jpeg
    - assets/img/food2.jpeg
    - assets/img/food3.jpeg
    - assets/img/food4.jpeg
    - assets/img/food5.jpeg
    - assets/img/food6.jpeg
    - assets/img/food7.jpeg
    - assets/img/food8.jpeg
    - assets/img/food9.jpeg
    - assets/img/food10.jpeg
    - assets/img/food11.jpeg
    - assets/img/food12.jpg
    - assets/img/lio.JPG
    - assets/img/mapsmania2.gif
    - assets/img/abuelos.jfif
    - assets/img/guacamaya.jpg
  fonts:
    - family: Asap
      fonts:
        - asset: fonts/Asap-Regular.ttf
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
    - family: Racing Sans One
      fonts:
        - asset: fonts/RacingSansOne-Regular.ttf
    - family: Fira Sans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf